### ISSUE TITLE
Not collecting many of the endpoints

### ISSUE THREAD

**Issue by deefdragon** [Katzen48/TwitchOpenApiGenerator#1]
I noticed this when I was checking to see if the parser was grabbing optional parameters (didn't see it in the code) and many of the examples I found were missing. `channel_points/custom_rewards` specifically only has PATCH, no post, get, or delete. I'm not sure what is the symptom and what the cause unfortunately.

**Comment by Katzen48** [comment]
You're totally right.
The Twitch API docs are very heterogeneous, so it's difficult to parse them.
I wanted to try parsing them in an automatic way first, before I start catching all the bugs.

If you want to contribute, feel free to do so.

**Comment by Katzen48** [comment]
All Endpoints are now included.
See: https://github.com/Katzen48/TwitchOpenApi/blob/main/swagger.yaml
And https://app.swaggerhub.com/apis/Katzen48/TwitchAPI/Helix
